<!-- <footer class="main-footer-container">
    <div class="container footer-section">
        <div class="footer-item">
            <div class="footer-item-header">
                <a href="{{route('site.index')}}">
                    <x-curator-glider :media="$logo" class="mw-100 mb-5" />
                </a>
            </div>
            <div>
                {!! $footer_description !!}
            </div>
        </div>
        @foreach($menu->links as $index => $child)
            @continue(!$child->status || !$child->has_children())
            <div class="footer-item">
                <div class="footer-item-header">
                    <h5>{{$child->title}}</h5>
                    <button
                            class="toggleButton mobile-responsive"
                            data-target="footer-link-{{$index}}"
                    >
                        <i class="fa-solid fa-plus"></i>
                        <i class="fa-solid fa-minus" style="display: none"></i>
                    </button>
                </div>
                <ul id="footer-link-{{$index}}">
                    @foreach($child->children as $grandson)
                        <li>
                            <a href="{{$grandson->link}}">{{$grandson->title}}</a>
                        </li>
                    @endforeach
                </ul>
            </div>
        @endforeach

    <div class="footer-copyright-container">
        <div class="footer-copyright-container-centered">
            <p class="d-flex flex-column align-items-center">@lang('site.copyright', ['year' => \Illuminate\Support\Carbon::now()->year, 'url' => '<a href="https://shiftcodes.net">ShiftCodes</a>'])</p>
            <div class="social-media-icons">
                @if ($twitter)
                    <a href="{{$twitter}}" target="_blank" rel="noopener noreferrer">
                        <i class="fa-brands fa-twitter"></i>
                    </a>
                @endif
                @if ($linkedin)
                    <a href="{{$linkedin}}" target="_blank" rel="noopener noreferrer">
                        <i class="fa-brands fa-linkedin-in"></i>
                    </a>
                @endif
                @if ($instagram)
                    <a href="{{$instagram}}" target="_blank" rel="noopener noreferrer">
                        <i class="fa-brands fa-instagram"></i>
                    </a>
                @endif
                @if ($youtube)
                    <a href="{{$youtube}}" target="_blank" rel="noopener noreferrer">
                        <i class="fa-brands fa-youtube"></i>
                    </a>
                @endif
                @if ($facebook)
                    <a href="{{$facebook}}" target="_blank" rel="noopener noreferrer">
                        <i class="fa-brands fa-facebook-f"></i>
                    </a>
                @endif
            </div>
        </div>
    </div>
</footer> -->

<footer class="main-footer-container">
        <div class="container footer-section">
          <div class="footer-item">
            <div class="footer-item-header">
              <a href="./index.html">
                <img
                  class="mw-100 mb-5"
                  src="./assets/imgs/home/logo-dark.png"
                  alt=""
                />
              </a>
            </div>
            <p>
              This text is an example of a text that can be replaced in the same
              space. This text was generated from the Arabic text generator,
              where you can generate such text or many other texts in addition
              to increasing the number of letters generated by the application.
            </p>
          </div>
          <div class="footer-item">
            <div class="footer-item-header">
              <h5>Important Links</h5>
              <button
                class="toggleButton mobile-responsive"
                data-target="about"
              >
                <i class="fa-solid fa-plus"></i>
                <i class="fa-solid fa-minus" style="display: none"></i>
              </button>
            </div>
            <ul id="about">
              <li>
                <a href=""> Terms and Conditions</a>
              </li>
              <li><a href=""> Privacy Policy </a></li>
              <li><a href=""> Admission Process </a></li>
              <li><a href=""> FAQs </a></li>
              <li><a href=""> Support Center</a></li>
            </ul>
          </div>
          <div class="footer-item">
            <div class="footer-item-header">
              <h5>Quick Links</h5>
              <button
                class="toggleButton mobile-responsive"
                data-target="about"
              >
                <i class="fa-solid fa-plus"></i>
                <i class="fa-solid fa-minus" style="display: none"></i>
              </button>
            </div>
            <ul id="about">
              <li>
                <a href=""> About Us</a>
              </li>
              <li><a href="">Our Services </a></li>
              <li><a href=""> Indicator </a></li>
              <li>
                <a href=""> Trading Companies</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="footer-copyright-container">
          <div class="footer-copyright-container-centered">
            <p>Copyright © ONE FOR ALL</p>
            <div class="social-media-icons">
              <a href="#">
                <i class="fa-brands fa-twitter"></i>
              </a>
              <a href="#">
                <i class="fa-brands fa-linkedin-in"></i>
              </a>
              <a href="#">
                <i class="fa-brands fa-instagram"></i>
              </a>
              <a href="#">
                <i class="fa-brands fa-youtube"></i>
              </a>
              <a href="#">
                <i class="fa-brands fa-facebook-f"></i>
              </a>
            </div>
          </div>
        </div>
      </footer>